In [1]:
import pandas as pd

In [2]:
kospi_real = pd.read_csv('../data/코스피실제주가_1112_1119.csv')
kospi_estimate = pd.read_csv('../data/코스피예측주가_1011_1120.csv')
kosdaq_real = pd.read_csv('../data/코스닥실제주가_1112_1119.csv')
kosdaq_estimate = pd.read_csv('../data/코스닥예측주가_1011_1120.csv')

In [3]:
# YYYY-MM-DD 형식으로 변환
kospi_real['Date'] = pd.to_datetime(kospi_real['Date']).dt.strftime('%Y-%m-%d')
kosdaq_real['Date'] = pd.to_datetime(kosdaq_real['Date']).dt.strftime('%Y-%m-%d')

In [4]:
# 행렬 전환
kospi_real_T = pd.DataFrame(kospi_real.T.reset_index().iloc[1:].values, columns=kospi_real.T.reset_index().iloc[0].values)
kospi_estimate_T = pd.DataFrame(kospi_estimate.T.reset_index().iloc[1:].values, columns=kospi_estimate.T.reset_index().iloc[0].values)
kosdaq_real_T = pd.DataFrame(kosdaq_real.T.reset_index().iloc[1:].values, columns=kosdaq_real.T.reset_index().iloc[0].values)
kosdaq_estimate_T = pd.DataFrame(kosdaq_estimate.T.reset_index().iloc[1:].values, columns=kosdaq_estimate.T.reset_index().iloc[0].values)

In [5]:
# 'Date' 컬럼 이름을 'Ticker'로 변경
kospi_real_T.columns = ['Ticker'] + list(kospi_real_T.columns[1:])
kospi_estimate_T.columns = ['Ticker'] + list(kospi_estimate_T.columns[1:])
kosdaq_real_T.columns = ['Ticker'] + list(kosdaq_real_T.columns[1:])
kosdaq_estimate_T.columns = ['Ticker'] + list(kosdaq_estimate_T.columns[1:])

In [6]:
# 'Ticker' 기준으로 오름차순 정렬
kospi_estimate_T = kospi_estimate_T.sort_values(by='Ticker', ascending=True).reset_index(drop=True)
kosdaq_estimate_T = kosdaq_estimate_T.sort_values(by='Ticker', ascending=True).reset_index(drop=True)

In [7]:
kospi_estimate_T.iloc[:, 23:-1]

   2024-11-12 2024-11-13 2024-11-14 2024-11-15 2024-11-18  2024-11-19
0   25419.385  25731.447  26030.592  26316.436  26588.746   26847.412
1   1014.4364  1013.4711   1012.526  1011.6009  1010.6955  1009.80945
2   14361.545  14350.722  14340.839  14331.822  14323.601    14316.11
3    542.8295  542.74774   542.6714   542.6003  542.53406    542.4725
4   3160.3767  3231.9712  3299.5212   3362.756  3421.5215    3475.768
5   1386.1735  1386.1768  1386.1765  1386.1747  1386.1721   1386.1697
6   1511.4178  1511.5731  1511.7185  1511.8545  1511.9814   1512.1002
7   21039.707  21013.035   20988.48  20965.932  20945.266   20926.365
8    8841.237   8836.614   8832.252   8828.144   8824.273    8820.639
9   4492.0635    4491.74   4491.435   4491.147   4490.875    4490.618
10  878.63007   876.6843   874.7604   872.8583  870.97833    869.1204
11  3466.9575  3465.1409  3463.4192  3461.7878  3460.2427   3458.7788
12  12628.191  12633.302  12638.126   12642.68  12646.976    12651.03
13  14910.723  14910.845  14910.961  14911.067  14911.168   14911.267
14  1730.5671   1730.416  1730.2748   1730.142  1730.0176    1729.901
15   71607.35  71607.305   71607.27   71607.24  71607.234    71607.23
16   3962.767  3961.6812  3960.7148  3959.8594  3959.1057   3958.4458

In [8]:
kospi_real_T.to_csv('../data/코스피실제주가_241112_241119.csv', index=False)
kospi_estimate_T.to_csv('../data/코스피예측주가_241112_241119.csv', index=False)
kosdaq_real_T.to_csv('../data/코스닥실제주가_241112_241119.csv', index=False)
kosdaq_estimate_T.to_csv('../data/코스닥예측주가_241112_241119.csv', index=False)